version: '3'

services:

  subquery-node-litmus-balance:
    image: onfinality/subql-node:v1.10.2
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: 
      DB_DATABASE: prod-litmus-balance 
      DB_HOST: 
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=public
      - --scale-batch-size=true
      - --batch-size=20 
      # - --log-level=debug
      # - --debug
      # - --profiler=true

